### ISSUE TITLE
The Irony made me laugh

### ISSUE THREAD

**Issue by just-Bri** [learn-co-curriculum/adding-responsive-features#1]
When I was scaling my window down during the lesson I noticed the github link get covered by the lesson title.

Here's a snippet of what I'm talking about: http://i.imgur.com/lmFRmpZ.png

**Comment by AnnJohn** [comment]
@kvignali this looks like a product issue? Can you pass it on to Labs?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
